name: React CI/CD with Yarn and Docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
env:
  REGISTRY_IMAGE: keke125/vault-guard-web-react

jobs:
  build-on-amd64:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64

    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            keke125/vault-guard-web-react

      - name: Set up Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          sudo docker build --platform linux/${{ matrix.platform }} -t ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }} .
          sudo docker push ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}

  build-on-arm64:
            runs-on: ${{ matrix.runner }}
            strategy:
              matrix:
                platform: [arm64]
                include:
                  - platform: arm64
                    runner: kix1-oracle-keke125
        
            steps:
              - uses: actions/checkout@v4
              - name: Docker meta
                id: meta
                uses: docker/metadata-action@v5
                with:
                  # list of Docker images to use as base name for tags
                  images: |
                    keke125/vault-guard-web-react
        
              - name: Set up Node LTS
                uses: actions/setup-node@v4
                with:
                  node-version: lts/*
        
              - name: Login to Docker Hub
                uses: docker/login-action@v3
                with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
        
              - name: Build and push Docker image
                run: |
                  sudo docker build --platform linux/${{ matrix.platform }} -t ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }} .
                  sudo docker push ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}