name: React CI/CD with Yarn and Docker

on:
  push:
    branches:
      - 'main'
    tags:
      - 'v*.*.*'
env:
  REGISTRY_IMAGE: keke125/vault-guard-web-react

jobs:
  build:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        platform: [amd64, arm64]
        include:
          - platform: amd64
            runner: github
          - platform: arm64
            runner: kix1-oracle-keke125

    steps:
      - uses: actions/checkout@v4
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to use as base name for tags
          images: |
            keke125/vault-guard-web-react

      - name: Set up Node LTS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          load: true
          tags: ${{ env.REGISTRY_IMAGE }}:${{ steps.meta.outputs.version }}